name: pyseir

channels:
- defaults
- conda-forge

dependencies:
- numpy
- pandas
- scipy
- python=3.7.3
- jupyterlab
- seaborn
- scikit-learn
- matplotlib
- pip
- iminuit
- fastparquet
- pip:
  - boto3
  - click
  - us
  - xlsxwriter
  - pymc3
  - astroid==2.3.0
  - certifi==2019.11.28
  - chardet==3.0.4
  - cycler==0.10.0
  - idna==2.9
  - isort==4.3.4
  - kiwisolver==1.1.0
  - lazy-object-proxy==1.3.1
  - GitPython==3.1.0
  - mccabe==0.6.1
  - plotly==4.5.4
  - pyshp==2.1.0
  - requests==2.23.0
  - simplejson==3.17.0
